Repository Nangman-Archive/CoPro_iOS, pull requests merged in 2024-05, with the labels that each got.

#13 [ Feature] #12 - 차단 유저 목록 조회 및 차단 해제 구현
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
  CoPro/CoPro/Network/DTO/MyProfile/BlockedDTO.swift
  CoPro/CoPro/Network/Router/MyProfileRouter/MyProfileRouter.swift
  CoPro/CoPro/Presentation/Login/View/LoginView.swift
  CoPro/CoPro/Presentation/MyProfile/Model/BlockedDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/View/BlockedUserListTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyProfileTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: enhancement

#15 [Feat] Add Manifest
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/PrivacyManifest.xcprivacy
Labels: documentation, enhancement

#17 [Feat] GAD 관련 이슈 1차 테스트
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro.xcodeproj/xcshareddata/xcschemes/CoPro.xcscheme
  CoPro/CoPro/Application/Info.plist
Labels: bug

#19 [Fix] App Store 심사 리젝 대응 (#18)
  CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: bug
